/**
 * Barrel re-export for the SPA's HTTP/data layer. Pages import the
 * `useApiClient` hook from here, never directly from the fetcher module.
 */
export {
  ApiError,
  consumeAdventureStream,
  createApi,
  fixtureFetcher,
  liveFetcher,
  makeFixtureStream,
  parseStreamEvent,
  withFixtureFallback,
  ADVENTURE_SETTINGS_FIXTURE,
  BRANCH_TREE_FIXTURE,
  CHARACTER_FIXTURE,
  CLOCK_TICK_FIXTURE,
  EFFECTIVE_SETTINGS_FIXTURE,
  NPC_ROSTER_FIXTURE,
  PLAYER_SETTINGS_FIXTURE,
  RECAP_FIXTURE,
  type AdventureDetailResponse,
  type AdventureListResponse,
  type AdventureResource,
  type AdventureSettingsRequest,
  type AdventureSettingsResource,
  type AdventureSettingsResponse,
  type AdventureSettingsUpdateRequest,
  type AdventureSettingGroup,
  type AiStatusResponse,
  type ApiClient,
  type ApiErrorBody,
  type AuthResponse,
  type BranchOpResponse,
  type BranchRedoRequest,
  type BranchResource,
  type BranchResponse,
  type BranchRetryRequest,
  type BranchRetryRequestBody,
  type BranchTreeNode,
  type BranchTreeResponse,
  type BranchTreeResponseShape,
  type BranchUndoRequest,
  type CharacterDetailResponse,
  type CharacterResource,
  type CharacterStat,
  type CharacterTrait,
  type ClockTickFixture,
  type CreateBranchRequest,
  type DiceRollFixture,
  type EffectiveSettingsResource,
  type EffectiveSettingsResponse,
  type Fetcher,
  type MechanicEventFixture,
  type NpcListResponse,
  type NpcRelationship,
  type NpcRelationshipKind,
  type NpcResource,
  type PlayerSettingsResource,
  type PlayerSettingsResponse,
  type PlayerSettingsUpdateRequest,
  type PlayerSettingsUpdateRequestBody,
  type PlayTurnChoiceRequest,
  type PlayTurnLegacyResponse,
  type PlayTurnResponse,
  type RecapResponse,
  type RecapResource,
  type RecapTurn,
  type ReferralResponse,
  type ReferralShareRequest,
  type RequestOptions,
  type ScenarioDetailLegacyResponse,
  type ScenarioDetailResponse,
  type ScenarioListLegacyResponse,
  type ScenarioListQuery,
  type ScenarioListResponse,
  type ScenarioVersionResponse,
  type SettingsLegacyResponse,
  type SettingsLegacyUpdateRequest,
  type SettingsLegacyUpdateResponse,
  type SettingsResponse,
  type SettingsUpdateRequest,
  type SettingGroupState,
  type SettingSource,
  type SignInRequest,
  type SignUpRequest,
  type StartAdventureRequest,
  type StreamEvent,
  type StreamHandlers,
  type SubmitTurnRequest,
  type TurnResponse,
  type TurnUsage,
  type TurnUsageEvent,
  type UserResponse,
  type WalletLegacyTopUpResponse,
  type WalletResponse,
  type WalletTopUpRequest,
} from './openapi';

export { ApiClientProvider } from './ApiClientContext';
export { ApiClientContext } from './context';
export { useApiClient } from './useApiClient';
