/**
 * Barrel re-export for the SPA's HTTP/data layer. Pages import the
 * `useApiClient` hook from here, never directly from the fetcher module.
 */
export {
  ApiError,
  consumeAdventureStream,
  createApi,
  fixtureFetcher,
  liveFetcher,
  makeFixtureStream,
  parseStreamEvent,
  withFixtureFallback,
  ADVENTURE_FIXTURE,
  IMAGE_CAROUSEL_FIXTURE,
  IMAGE_JOB_COMPLETED_FIXTURE,
  IMAGE_JOB_QUEUED_FIXTURE,
  LORE_FIXTURE,
  PINNED_MEMORY_FIXTURE,
  RECAP_FIXTURE,
  type AdventureDetailResponse,
  type AdventureListResponse,
  type AdventureResource,
  type AiStatusResponse,
  type ApiClient,
  type ApiErrorBody,
  type AuthResponse,
  type BranchResponse,
  type CreateBranchRequest,
  type Fetcher,
  type GenerateImageRequest,
  type ImageAsset,
  type ImageCarouselResponse,
  type ImageCarouselResponseShape,
  type ImageJobResponse,
  type ImageJobResponseShape,
  type ImageJobStatus,
  type ImageJobStatusShape,
  type LoreEntry,
  type LoreListQuery,
  type LoreListResponse,
  type LoreListResponseShape,
  type PinnedMemory,
  type PinnedMemoryCreateRequest,
  type PinnedMemoryListResponse,
  type PinnedMemoryListResponseShape,
  type PlayTurnChoiceRequest,
  type PlayTurnLegacyResponse,
  type PlayTurnResponse,
  type RecapResource,
  type RecapResponse,
  type RecapTurn,
  type ReferralResponse,
  type ReferralShareRequest,
  type RequestOptions,
  type ScenarioDetailLegacyResponse,
  type ScenarioDetailResponse,
  type ScenarioListLegacyResponse,
  type ScenarioListQuery,
  type ScenarioListResponse,
  type ScenarioVersionResponse,
  type SettingsLegacyResponse,
  type SettingsLegacyUpdateRequest,
  type SettingsLegacyUpdateResponse,
  type SettingsResponse,
  type SettingsUpdateRequest,
  type SignInRequest,
  type SignUpRequest,
  type StartAdventureRequest,
  type StreamEvent,
  type StreamHandlers,
  type SubmitTurnRequest,
  type TurnResponse,
  type TurnUsage,
  type TurnUsageEvent,
  type UserResponse,
  type WalletLegacyTopUpResponse,
  type WalletResponse,
  type WalletTopUpRequest,
} from './openapi';

export { ApiClientProvider } from './ApiClientContext';
export { ApiClientContext } from './context';
export { useApiClient } from './useApiClient';
